package uk.ac.aston.ssp.spServer;

import java.util.*;
import java.net.*;
import java.io.*;

public class Client {
	
	private static final String SERVER_IP = "127.0.0.1";
	private static final int SERVER_PORT = 43221;
	
	private static Client clientID;
	
	public static void main(String[] args) throws IOException{
		// TODO Auto-generated method stub
		
		
		
		try(
		Socket socket = new Socket(SERVER_IP, SERVER_PORT);
		
		PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
		BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
		BufferedReader stdIn = new BufferedReader(new InputStreamReader(System.in));
		
		){
			
		//Reads userInput
		System.out.println("INTER USER INPUT");
		String userInput;
		//Reads Server's response
		
		while((userInput = stdIn.readLine()) != null) {
			//Sends out client request
			out.println(userInput);
			
			//Prints Server's response
			System.out.println("SERVER RESPONSE: "+ in.readLine());
			
			}
		
		
		}catch(UnknownHostException e) {
			
			System.out.println("Unknown host Exception");
			System.exit(1);
			
		}catch(IOException e) {
			System.out.println("Coudn't get I/O for the connection to host");
			System.exit(1);
		}
		
	}
	
	/*
	 * getter method for clientID which will be generated by the server.
	 * 
	 * 
	public int getClientID() {
		
		return clientID;
	}
	*/

}
